version: '2'
services:
  tracing-proxy:
    build:
      context: .
    container_name: tracing-proxy
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    ports:
      - "8081:8081"
    expose:
      - "8081"
    links:
      - zipkin
  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
