version: '2'
services:
  sample-app:
    build:
      context: .
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
      - ~/dev-certs:/etc/ssl # should point to local dev certs
    ports:
      - "8081:8081"
      - "8082:8082"
    expose:
      - "8081"
      - "8082"